language: rust
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: 
      - nightly
      - beta
  fast_finish: true

script:
  - cargo build --verbose --all
  - cargo test --verbose --all