dist: trusty
sudo: false

matrix:
  include:
    # Travis setup for rust
    - language: rust
      before_script:
        - cd rust
      script:
        - ./script/run.sh
    
    # setup java
    - language: java
      jdk: oraclejdk8
      before_script: 
        - cd java
      script:
        - ./script/run.sh

  fast_finish: true


